name: app_leitura
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_tts: ^3.8.3
  lottie: ^3.1.2
  audioplayers: ^6.0.0
  smooth_page_indicator: ^1.2.0
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  shared_preferences: ^2.3.1
  workmanager: ^0.5.2
  flutter_svg: ^2.0.10+1
  awesome_notifications: ^0.9.3+1
  firebase_messaging: ^15.0.4
  overlay_support: ^2.1.0
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.4.1
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_tts:

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/cards/
    - assets/icons/
    - assets/icons/themes/
    - assets/icons/themes/theme1/
    - assets/icons/themes/theme2/
    - assets/icons/themes/theme3/
    - assets/animations/

flutter_native_splash:
  color: "#00008B"  # Cor de fundo da splash screen
  image: assets/backgrounds/splash.png  # Caminho para a imagem da splash screen
  android: true  # Ativar para Android
  ios: true  # Ativar para iOS
  android_gravity: center  # (Opcional) Alinhar a imagem ao centro
  ios_content_mode: center  # (Opcional) Alinhar a imagem ao centro no iOS
